docs/DeveloperGuide.md, docs/UserGuide.md
- The diagram can be done under a new issue because it doesn't only apply to the `tutorial add` command
- Use cases can be updated collectively under #47
=> Add documentation for `tutorial add` command

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
=> Move reckless `arePrefixesPresent` into `ArgumentMultimap::allPresent`

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
=> Check that a tutorial exist before adding a student

docs/DeveloperGuide.md
Team has agreed to remove the Feature List from the DG as it is deemed as not an essential component of the DG.
=> Remove feature list from DG

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalStudentsInclTutorials.json, src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/testutil/TypicalStudents.java
Fixes #105.
Tests modified to use existing tutorials.
Add command now adds a student, with only existing tutorials (if any).
Edit command proceeds with edits made to student, with only existing tutorials (if any).
Edit: changes made to edit command behaviour
=> Default tutorials added to SampleDataUtil.java

build.gradle, docs/UserGuide.md
I've deployed the changes here: https://whyare.github.io/tp/
lmao I'll just request review all of y'all to make sure the UG is robust af
=> Update user guide to show the most updated information

src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/Student.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
If a tutorial slot allocated to students is deleted, the tutorial slot is deleted from the students as well.
=> Delete tutorial for students

src/main/java/seedu/address/logic/commands/AddCommand.java
=> Change add student help message

src/main/java/seedu/address/logic/commands/FindTutorialCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/TutorialCard.java, src/main/java/seedu/address/ui/TutorialListPanel.java
Reverted the tutorial list to a previous working version. i.e. Uses ```Tutorial``` instead of ```TutorialWithStudents```
Regression: Tutorial list now does not show students in each tutorial class
=> Tutorial list bug fix

src/main/java/seedu/address/logic/commands/AddStudentToTutorialCommand.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/model/NavigationMode.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java
Fixes #129.
Navigation mode remains as STUDENT after adding a student to tutorial.
=> Fix navigation mode to student after add to tutorial

src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java, src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/AddTutorialCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/AssignmentParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/NavigationMode.java, src/main/java/seedu/address/model/tutorial/Assignment.java, src/main/java/seedu/address/model/tutorial/Tutorial.java, src/main/java/seedu/address/storage/JsonAdaptedAssignment.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/TutorialCard.java, src/main/resources/view/TutorialListCard.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java, src/test/java/seedu/address/logic/parser/MarkAttendanceParserTest.java
You can view the assignments in the `TUTORIAL` view
=> Add `assignment add` command

src/main/java/seedu/address/logic/commands/SetSubmissionCommand.java, src/main/java/seedu/address/logic/commands/SubmissionCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/SetSubmissionCommandParser.java, src/main/java/seedu/address/logic/parser/SubmissionParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/model/submission/Submission.java, src/main/java/seedu/address/model/submission/SubmissionStatus.java, src/main/java/seedu/address/model/tutorial/Assignment.java, src/main/java/seedu/address/model/tutorial/Tutorial.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
The syntax is `submission set STATE t/TUTORIAL_NAME a/ASSIGNMENT_NAME s/STUDENT_INDEX...`
STATE is `submitted`, `not-submitted`, `graded` (case insensitive)
=> Submit assignment feature

src/main/java/seedu/address/logic/commands/export/ExportCommand.java, src/main/java/seedu/address/logic/commands/export/ExportStudentsCommand.java, src/main/java/seedu/address/logic/commands/export/ExportTutorialsCommand.java
Fixes #247.
Changed the export messages to be consistent with each other.
=> Export Message Inconsistency

docs/DeveloperGuide.md
=> Update DG User Stories

docs/DeveloperGuide.md, docs/UserGuide.md
- Fix TOC and formatting in User Guide
- Add missing use cases
=> Update misellaneous information in DG

docs/DevOps.md, docs/DeveloperGuide.md, docs/_config.yml, docs/index.md
=> Fix URL to point to our repo instead of `se-edu/addressbook-level3`

src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
=> Process assignments even though they fail

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/attendance/Attendance.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/model/tutorial/Assignment.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/testutil/StudentUtil.java
This should count as 93 LoC
- Test the submission and attendance list works correctly:
- `attendance list` and `submission list`: To like preload the list info
- `edit 1 n/yes`: Edit student name (actually please try other fields cos I haven't)
- Test the absence of `t/` flag
- Try to create a student with `t/` flag
- Try to edit student with `t/` flag
- Verify it solves #308
=> Disable `t/` flag in add and edit; edit student mutably so attendance list and submission list works fine

src/main/java/seedu/address/commons/core/index/Index.java, src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java, src/main/java/seedu/address/logic/commands/AddStudentToTutorialCommand.java, src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteStudentFromTutorialCommand.java, src/main/java/seedu/address/logic/commands/SetSubmissionCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/AddStudentToTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/SetSubmissionCommandTest.java
LoC: 50
Add tests to check for multiple indices:
- Add Assignment
- Delete Assignment
- Add student to tutorial
- Delete student from tutorial
- Set submission status
- Mark attendance
- Unmark attendance
=> Fix issue with multiple indexes

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddTutorialCommand.java, src/main/java/seedu/address/logic/parser/AddTutorialCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java, src/main/java/seedu/address/model/tutorial/Assignment.java, src/main/java/seedu/address/model/tutorial/Tutorial.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java, src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTutorialCommandParserTest.java, src/test/java/seedu/address/model/tutorial/AssignmentTest.java
Checks
- Assignment name is alphanumeric, underscore, hyphen, space, 1 to 35 chars
- Tutorial name is alphanumeric, underscore, hyphen, 1 to 15 chars
- Spaces around assignment name and tutorial names are stripped
=> Assignment and tutorial name sanitisation and validation

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/storage/json/JsonAdaptedStudent.java, src/test/data/JsonSerializableAddressBookTest/duplicateAlice.json, src/test/data/JsonSerializableAddressBookTest/missingAlice.json, src/test/data/JsonSerializableAddressBookTest/missingCS2103T1.json, src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json, src/test/java/seedu/address/storage/json/JsonAdaptedStudentTest.java, src/test/java/seedu/address/testutil/TypicalAddressBook.java
=> Student description not saved to storage

docs/DeveloperGuide.md
=> Edit Command Sequence Diagram a bit too small

src/main/java/seedu/address/logic/Messages.java
=> Tutorials in student description after editing not separated clearly
